<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" language="java" %><%@ page import="com.hotel.model.User" %><%@ page import="com.hotel.model.Room" %><%@ page import="com.hotel.model.Service" %><%@ page import="java.util.List" %><%@ page import="java.text.NumberFormat" %><%@ page import="java.util.Locale" %>
<%
HttpSession sess=request.getSession(false);User currentUser=sess!=null?(User)sess.getAttribute("currentUser"):null;List<Room>availableRooms=(List<Room>)request.getAttribute("availableRooms");List<Service>services=(List<Service>)request.getAttribute("services");NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("vi","VN"));
%>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nestora Hotel</title><link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css"></head><body>
<header class="public-header"><div class="public-brand"><div class="brand-logo" aria-hidden="true"><img src="<%=request.getContextPath()%>/assets/icons/logo.svg" alt=""></div><div class="brand-name"><strong>NESTORA</strong><small>HOTEL MANAGER</small></div></div><nav class="public-nav"><a class="active" href="<%=request.getContextPath()%>/home">Trang chủ</a><%if(currentUser!=null){if("Admin".equals(currentUser.getRole())||"Receptionist".equals(currentUser.getRole())){%><a href="<%=request.getContextPath()%>/home">Quản trị</a><%}else{%><a href="<%=request.getContextPath()%>/bills?action=mybills">Phòng đã đặt</a><%}%><a href="<%=request.getContextPath()%>/logout">Đăng xuất</a><%}else{%><a class="btn btn-primary" href="<%=request.getContextPath()%>/login">Đăng nhập</a><%}%></nav></header>
<main class="public-content"><section class="hero"><h1>Trải nghiệm lưu trú thuận tiện cùng Nestora</h1><p>Khám phá phòng trống, đặt phòng và theo dõi hóa đơn trên cùng một hệ thống.</p><%if(currentUser==null){%><a class="btn btn-primary" href="<%=request.getContextPath()%>/login">Đăng nhập để đặt phòng</a><%}%></section>
<div class="page-head"><div><h2 class="page-title">Phòng đang sẵn sàng</h2><p class="page-desc">Dữ liệu thật từ hệ thống quản lý phòng.</p></div></div><div class="card-grid"><%if(availableRooms!=null&&!availableRooms.isEmpty()){for(Room r:availableRooms){%><article class="card"><div class="card-image"></div><div class="card-body"><h3 class="card-title">Phòng <%=r.getRoomNumber()%> · <%=r.getRoomType().getName()%></h3><div class="card-price"><%=money.format(r.getRoomType().getPricePerDay())%> / ngày</div><p class="card-desc"><%=r.getDescription()!=null?r.getDescription():r.getRoomType().getDescription()%></p><%if(currentUser!=null){%><a class="btn btn-primary btn-block" href="<%=request.getContextPath()%>/rooms?action=bookForm&roomId=<%=r.getId()%>">Đặt phòng</a><%}else{%><a class="btn btn-outline btn-block" href="<%=request.getContextPath()%>/login">Đăng nhập để đặt</a><%}%></div></article><%}}else{%><div class="surface empty"><strong>Hiện chưa có phòng trống</strong>Vui lòng quay lại sau.</div><%}%></div>
<div class="page-head" style="margin-top:30px"><div><h2 class="page-title">Dịch vụ khách sạn</h2><p class="page-desc">Các tiện ích có thể sử dụng trong thời gian lưu trú.</p></div></div><div class="card-grid"><%if(services!=null){for(Service s:services){%><article class="card"><div class="card-body"><h3 class="card-title"><%=s.getName()%></h3><div class="card-price"><%=money.format(s.getPrice())%></div><p class="card-desc"><%=s.getDescription()%></p></div></article><%}}%></div></main></body></html>
