<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@ page import="com.hotel.model.User" %><%@ page import="com.hotel.model.Room" %><%@ page import="java.util.List" %><%@ page import="java.text.NumberFormat" %><%@ page import="java.util.Locale" %>
<%
HttpSession sess=request.getSession(false); User currentUser=sess!=null?(User)sess.getAttribute("currentUser"):null;
if(currentUser==null||(!"Admin".equals(currentUser.getRole())&&!"Receptionist".equals(currentUser.getRole()))){response.sendRedirect(request.getContextPath()+"/home");return;}
List<Room> rooms=(List<Room>)request.getAttribute("rooms"); NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("vi","VN")); boolean isAdmin="Admin".equals(currentUser.getRole()); String activeMenu="rooms";
%>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Danh sách phòng - Nestora</title><link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css"></head><body>
<div class="admin-layout"><%@ include file="../WEB-INF/jspf/admin-sidebar.jspf" %><main class="main-shell"><%@ include file="../WEB-INF/jspf/admin-topbar.jspf" %><section class="content"><div class="content-inner">
<div class="page-head"><div><div class="breadcrumb">Vận hành / Danh sách phòng</div><h1 class="page-title">Danh sách phòng</h1><p class="page-desc">Quản lý thông tin, giá thuê và trạng thái phòng.</p></div><div class="page-actions"><a class="btn btn-outline" href="<%=request.getContextPath()%>/admin/room-map.jsp">Sơ đồ phòng</a><%if(isAdmin){%><a class="btn btn-primary" href="<%=request.getContextPath()%>/rooms?action=add">＋ Thêm mới</a><%}%></div></div>
<section class="surface">
<div class="table-tools"><div class="search-box"><input type="search" placeholder="Tìm theo mã phòng, loại phòng hoặc mô tả..."><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/></svg></div><div class="admin-filter-group"><select class="admin-filter-select" data-admin-filter aria-label="Lọc trạng thái phòng"><option value="">Tất cả trạng thái</option><option value="Phòng trống">Phòng trống</option><option value="Đang sử dụng">Đang sử dụng</option><option value="Bảo trì">Bảo trì</option></select></div><div class="table-meta"><span><%=rooms!=null?rooms.size():0%> phòng</span></div></div>
<%if(rooms!=null&&!rooms.isEmpty()){%><div class="table-wrap"><table><thead><tr><th>MÃ PHÒNG</th><th>LOẠI PHÒNG</th><th>GIÁ / NGÀY</th><th>SỨC CHỨA</th><th>TRẠNG THÁI</th><th>MÔ TẢ</th><th>THAO TÁC</th></tr></thead><tbody>
<%for(Room r:rooms){%><tr><td class="table-primary">#<%=r.getRoomNumber()%></td><td class="table-strong"><%=r.getRoomType().getName()%></td><td><%=money.format(r.getRoomType().getPricePerDay())%></td><td><%=r.getRoomType().getCapacity()%> người</td><td><%if("Available".equals(r.getStatus())){%><span class="status success">Phòng trống</span><%}else if("Booked".equals(r.getStatus())){%><span class="status info">Đang sử dụng</span><%}else{%><span class="status warning">Bảo trì</span><%}%></td><td><%=r.getDescription()!=null?r.getDescription():"-"%></td><td><div class="row-actions"><a class="btn btn-outline btn-icon" href="<%=request.getContextPath()%>/rooms?action=edit&id=<%=r.getId()%>">✎</a><%if(isAdmin){%><a class="btn btn-danger btn-icon" href="<%=request.getContextPath()%>/rooms?action=delete&id=<%=r.getId()%>" onclick="return confirm('Xóa phòng này?')">×</a><%}%></div></td></tr><%}%>
</tbody></table></div><div class="pagination"><span class="page-number active">1</span></div><%}else{%><div class="empty"><strong>Chưa có phòng</strong>Hãy thêm phòng đầu tiên vào hệ thống.</div><%}%>
</section></div></section></main></div><script src="<%=request.getContextPath()%>/js/app.js"></script></body></html>
